# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sachin Rastogi
tagline:          'Data Scientist'
description:      'Data Scientist'
url:              https://sachin-rastogi.github.io
baseurl:          /

author:
  name:           'Sachin Rastogi'
  url:            https://sachin-rastogi.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sachin-rastogi
