# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sasha Kapralov
tagline:          'Data Scientist'
description:      'Data Scientist'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Sasha Kapralov'
  url:            https://sasha-kap.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sasha-kap
